development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://#{Settings.redis_host}:6379/1" } %>
  channel_prefix: rails365_production

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://#{Settings.redis_host}:6379/1" } %>
  channel_prefix: rails365_production
